package com.soluna.ktvisual.report

import java.nio.file.Path

/**
 * A file generated by visual diagnostics.
 *
 * Test frameworks can attach these paths to reports without depending on
 * OpenCV-specific types.
 */
data class VisualArtifact(
    val name: String,
    val path: Path,
    val description: String
)
